### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by PetroLeh** [amandahamynen/maze_solver#3]
(edit: ladattu 30.4. klo 8.52)

Moi!

Näyttää oikein hyvältä!
Ainoastaan DeadEndFillerin luo_ruudukko-metodiin piti lisäillä pari tulostusta itselleni selventämään miten se ruudukko rakentuukaan.
Ajattelin, että ehkä pari sisäkkäistä for-silmukkaa toimisi ja olisi selkeämpi? Ei tosin vaikuta toimivuuteen tai tehokkuuteenkaan.

Ei ole koodista tuon kummemmin huomioita, selkeää ja siistiä!

Tuosta Linux-visualisointiongelmasta:
Lisäilin taas vähän tulostusta. Ongelma on tuossa pyamaze-kirjastossa, alla traceback virheilmoituksesta. Siellä on tuo `self._win.state('zoomed')` - Näyttää siltä, että Linux ei tue kyseistä 'zoomed' -tilaa (https://www.oreilly.com/library/view/python-gui-programming/9781788835886/984b9be2-7c26-445e-9f94-ba8fef208ee0.xhtml). Kävin vaihtamassa tuolta pyamaze.py tiedostosta kyseisen rivin muotoon `self._win.state('normal')` ja ainakin minulla toimii.

Traceback (most recent call last):

  File "/home/lehtonep/Documents/tiralabra/vertaisarvioitava/maze_solver-main/src/app.py", line 26, in visualise_tremaux
    m.CreateMaze()
  File "/home/lehtonep/Documents/tiralabra/vertaisarvioitava/maze_solver-main/venv/lib/python3.8/site-packages/pyamaze/pyamaze.py", line 599, in CreateMaze
    self._drawMaze(self.theme)
  **File "/home/lehtonep/Documents/tiralabra/vertaisarvioitava/maze_solver-main/venv/lib/python3.8/site-packages/pyamaze/pyamaze.py", line 622, in _drawMaze
    self._win.state('zoomed')**
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2220, in wm_state
    return self.tk.call('wm', 'state', self._w, newstate)
tkinter.TclError: bad argument "zoomed": must be normal, iconic, or withdrawn

**bad argument "zoomed": must be normal, iconic, or withdrawn**

**Comment by PetroLeh** [comment]
Kyseinen virhe tapahtuu siis tuossa CreateMaze()-metodissa, mutta App-luokan run-metodissa oleva try-lohko nappaa poikkeuksen. Sinne kannattaa laittaa vaikka hieman aputulostuksia, jos haluat tutkia tarkemmin.

**Comment by amandahamynen** [comment]
KIITOS todella paljon! Aloin jo olemaan todella epätoivoinen tämän suhteen, mutta on helpottavaa kuulla, että se ilmeisesti ratkeaa noinkin "yksinkertaisella" tavalla! :D Perehdyn tähän paremmin lähipäivinä ja yritän saada tuon korjattua tänne githubin puolelle (tällä hetkellä tiedosto pyamaze.py on venv-kansion uumenissa, jotka eivät löydy githubista). Kiitos jälleen kerran!
